WITH FIRST_GEN AS (
    SELECT ID
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
),
SECOND_GEN AS (
    SELECT ECOLI_DATA.ID
    FROM ECOLI_DATA
    INNER JOIN FIRST_GEN
    ON FIRST_GEN.ID = ECOLI_DATA.PARENT_ID
)
SELECT ECOLI_DATA.ID
FROM ECOLI_DATA
INNER JOIN SECOND_GEN
    ON SECOND_GEN.ID = ECOLI_DATA.PARENT_ID;