-- 코드를 작성해주세요
SELECT COUNT(n.FISH_TYPE) AS FISH_COUNT, n.FISH_NAME
FROM FISH_NAME_INFO AS n
INNER JOIN FISH_INFO AS i
ON n.FISH_TYPE = i.FISH_TYPE
GROUP BY n.FISH_TYPE, n.FISH_NAME
ORDER BY COUNT(n.FISH_TYPE) DESC;