-- 코드를 작성해주세요
SELECT SUM(SCORE) AS SCORE, e.EMP_NO, e.EMP_NAME, e.POSITION, e.EMAIL
FROM HR_EMPLOYEES AS e
INNER JOIN HR_GRADE AS g
ON e.EMP_NO = g.EMP_NO
GROUP BY YEAR, EMP_NO
ORDER BY SCORE DESC
LIMIT 1;